### ISSUE TITLE
ListRecords max. 1000 records?

### ISSUE THREAD

**Issue by nicowitteman** [Rijksmuseum/oai-issues#1]
Mij valt op dat sinds enige tijd niet meer dan 10000 rijen worden teruggegeven met ListRecords, dat wil zeggen met resumptiontoken MXw5OTgwfG9haV9kY3wyMDE1LTA2LTI1VDE2OjM5OjMxfHw= krijg ik nog 20 records, met als laatste regel
`      <resumptionToken completeListSize="618099" cursor="9980">MXwxMDAwMHxvYWlfZGN8MjAxNS0wNi0yNVQxNjozOTozMXx8</resumptionToken>`
, maar met die laatste resumptiontoken krijg ik dit resultaat:

```
<OAI-PMH xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd" xmlns="http://www.openarchives.org/OAI/2.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:rm="http://rijksmuseum.nl/collection" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <responseDate>2017-12-12T18:49:04Z</responseDate>
   <request verb="ListRecords" resumptionToken="MXwxMDAwMHxvYWlfZGN8MjAxNS0wNi0yNVQxNjozOTozMXx8" xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:europeana="http://www.europeana.eu/schemas/ese/">https://www.rijksmuseum.nl/api/oai/sMS5lDSP</request>
   <ListRecords xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:europeana="http://www.europeana.eu/schemas/ese/">
      <resumptionToken completeListSize="0" cursor="10000"/>
   </ListRecords>
</OAI-PMH>

```
Is hier iets veranderd? 
                
Overigens staat op https://www.rijksmuseum.nl/nl/api/uitleg-rijksmuseum-oai-api dat een teruggegeven recordset uit 100 reocords bestaat, niet de 20 die het werkelijk zijn.

**Comment by rasvaan** [comment]
Een tijd geleden hebben we de index van de back-end veranderd en daarbij werd de limiet van 1000 records geïntroduceerd. Het probleem zou inmiddels verholpen moeten zijn. Wanneer dat niet het geval mocht zijn dan horen we dat graag. We hebben ook nieuwe documentatie voor de OAI-PMH API online gezet: http://rijksmuseum.github.io/oai
Daarin is het aantal geretourneerde objecten ook aangepast.
